name: NodeSeek 自动签到

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    # 每天北京时间 0:10 (UTC 16:10)
    - cron: '00 16 * * *'
    # 每天北京时间 12:20 (UTC 4:20)
    - cron: '00 4 * * *'
    - cron: '00 10 * * *'

jobs:
  run-nodeseek-daily:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome and dependencies
        run: |
          # 安装依赖
          sudo apt-get update
          sudo apt-get install -y wget gnupg xvfb
          
          # 添加 Google Chrome 官方源
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          
          # 安装稳定版 Chrome
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          echo "Chrome version:"
          google-chrome --version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NodeSeek script
        env:
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          NS_RANDOM: ${{ secrets.NS_RANDOM }}
          NS_COMMENT_URL: ${{ secrets.NS_COMMENT_URL }}
          NS_DELAY_MIN: ${{ vars.NS_DELAY_MIN }}
          NS_DELAY_MAX: ${{ vars.NS_DELAY_MAX }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          HEADLESS: "false"
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python nodeseek_daily.py
